### ISSUE TITLE
[bug] .xlsx/.xlsm のセルコメント加工処理でエラー発生

### ISSUE THREAD

**Issue by nmby** [nmby/hogandiff3#54]
2021/2/4 利用者の方からのバグ情報提供あり。

- OS：Windows10
- バージョン：v0.7.7
- ファイル形式：.xlsm
- 発生エラー：『Excelブックへの着色、保存、表示に失敗しました。』
- スタックトレース：

```
xyz.hotchpotch.hogandiff.excel.ExcelHandlingException: xl/drawings/vmlDrawing2.vml エントリの処理に失敗しました。
	at xyz.hotchpotch.hogandiff.excel.stax.XSSFBookPainterWithStax.processCommentDrawingEntry(XSSFBookPainterWithStax.java:619)
	at xyz.hotchpotch.hogandiff.excel.stax.XSSFBookPainterWithStax.processWorksheetEntries(XSSFBookPainterWithStax.java:472)
	at xyz.hotchpotch.hogandiff.excel.stax.XSSFBookPainterWithStax.paintAndSave(XSSFBookPainterWithStax.java:304)
	at xyz.hotchpotch.hogandiff.excel.common.CombinedBookPainter.paintAndSave(CombinedBookPainter.java:107)
	at xyz.hotchpotch.hogandiff.AppTask.showPaintedSheets2(AppTask.java:377)
	at xyz.hotchpotch.hogandiff.AppTask.showPaintedSheets(AppTask.java:318)
	at xyz.hotchpotch.hogandiff.AppTask.call(AppTask.java:104)
	at xyz.hotchpotch.hogandiff.AppTask.call(AppTask.java:37)
	at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.RuntimeException: javax.xml.stream.XMLStreamException: ParseError at [row,col]:[22,9]
Message: 要素タイプ"br"は、対応する終了タグ"</br>"で終了する必要があります。
	at xyz.hotchpotch.hogandiff.excel.stax.readers.BufferingReader.hasNext(BufferingReader.java:89)
	at xyz.hotchpotch.hogandiff.excel.stax.readers.PaintDiffOrRedundantCommentsReader.seekNext(PaintDiffOrRedundantCommentsReader.java:102)
	at xyz.hotchpotch.hogandiff.excel.stax.readers.BufferingReader.hasNext(BufferingReader.java:87)
	at java.xml/com.sun.xml.internal.stream.writers.XMLEventWriterImpl.add(Unknown Source)
	at xyz.hotchpotch.hogandiff.excel.stax.XSSFBookPainterWithStax.processCommentDrawingEntry(XSSFBookPainterWithStax.java:616)
	... 14 more
Caused by: javax.xml.stream.XMLStreamException: ParseError at [row,col]:[22,9]
Message: 要素タイプ"br"は、対応する終了タグ"</br>"で終了する必要があります。
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLStreamReaderImpl.next(Unknown Source)
	at java.xml/com.sun.xml.internal.stream.XMLEventReaderImpl.peek(Unknown Source)
	at xyz.hotchpotch.hogandiff.excel.stax.readers.CloseAndUnpaintCommentsReader.seekNext(CloseAndUnpaintCommentsReader.java:63)
	at xyz.hotchpotch.hogandiff.excel.stax.readers.BufferingReader.hasNext(BufferingReader.java:87)
	... 18 more
xyz.hotchpotch.hogandiff.excel.ExcelHandlingException: Excelファイルのコピーに失敗しました：▲▲▲■■■.xlsm -> ●●●【A】■■■.xlsm
	at xyz.hotchpotch.hogandiff.excel.poi.usermodel.BookPainterWithPoiUserApi.paintAndSave(BookPainterWithPoiUserApi.java:167)
	at xyz.hotchpotch.hogandiff.excel.common.CombinedBookPainter.paintAndSave(CombinedBookPainter.java:107)
	at xyz.hotchpotch.hogandiff.AppTask.showPaintedSheets2(AppTask.java:377)
	at xyz.hotchpotch.hogandiff.AppTask.showPaintedSheets(AppTask.java:318)
	at xyz.hotchpotch.hogandiff.AppTask.call(AppTask.java:104)
	at xyz.hotchpotch.hogandiff.AppTask.call(AppTask.java:37)
	at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.nio.file.FileAlreadyExistsException: ●●●【A】■■■.xlsm
	at java.base/sun.nio.fs.WindowsFileCopy.copy(Unknown Source)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.copy(Unknown Source)
	at java.base/java.nio.file.Files.copy(Unknown Source)
	at xyz.hotchpotch.hogandiff.excel.poi.usermodel.BookPainterWithPoiUserApi.paintAndSave(BookPainterWithPoiUserApi.java:157)
	... 12 more
xyz.hotchpotch.hogandiff.excel.ExcelHandlingException: 処理に失敗しました：▲▲▲■■■.xlsm -> ●●●【A】■■■.xlsm
	at xyz.hotchpotch.hogandiff.excel.common.CombinedBookPainter.paintAndSave(CombinedBookPainter.java:100)
	at xyz.hotchpotch.hogandiff.AppTask.showPaintedSheets2(AppTask.java:377)
	at xyz.hotchpotch.hogandiff.AppTask.showPaintedSheets(AppTask.java:318)
	at xyz.hotchpotch.hogandiff.AppTask.call(AppTask.java:104)
	at xyz.hotchpotch.hogandiff.AppTask.call(AppTask.java:37)
	at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
	Suppressed: xyz.hotchpotch.hogandiff.excel.ExcelHandlingException: xl/drawings/vmlDrawing2.vml エントリの処理に失敗しました。
		at xyz.hotchpotch.hogandiff.excel.stax.XSSFBookPainterWithStax.processCommentDrawingEntry(XSSFBookPainterWithStax.java:619)
		at xyz.hotchpotch.hogandiff.excel.stax.XSSFBookPainterWithStax.processWorksheetEntries(XSSFBookPainterWithStax.java:472)
		at xyz.hotchpotch.hogandiff.excel.stax.XSSFBookPainterWithStax.paintAndSave(XSSFBookPainterWithStax.java:304)
		at xyz.hotchpotch.hogandiff.excel.common.CombinedBookPainter.paintAndSave(CombinedBookPainter.java:107)
		... 11 more
	Caused by: java.lang.RuntimeException: javax.xml.stream.XMLStreamException: ParseError at [row,col]:[22,9]
Message: 要素タイプ"br"は、対応する終了タグ"</br>"で終了する必要があります。
		at xyz.hotchpotch.hogandiff.excel.stax.readers.BufferingReader.hasNext(BufferingReader.java:89)
		at xyz.hotchpotch.hogandiff.excel.stax.readers.PaintDiffOrRedundantCommentsReader.seekNext(PaintDiffOrRedundantCommentsReader.java:102)
		at xyz.hotchpotch.hogandiff.excel.stax.readers.BufferingReader.hasNext(BufferingReader.java:87)
		at java.xml/com.sun.xml.internal.stream.writers.XMLEventWriterImpl.add(Unknown Source)
		at xyz.hotchpotch.hogandiff.excel.stax.XSSFBookPainterWithStax.processCommentDrawingEntry(XSSFBookPainterWithStax.java:616)
		... 14 more
	Caused by: javax.xml.stream.XMLStreamException: ParseError at [row,col]:[22,9]
Message: 要素タイプ"br"は、対応する終了タグ"</br>"で終了する必要があります。
		at java.xml/com.sun.org.apache.xerces.internal.impl.XMLStreamReaderImpl.next(Unknown Source)
		at java.xml/com.sun.xml.internal.stream.XMLEventReaderImpl.peek(Unknown Source)
		at xyz.hotchpotch.hogandiff.excel.stax.readers.CloseAndUnpaintCommentsReader.seekNext(CloseAndUnpaintCommentsReader.java:63)
		at xyz.hotchpotch.hogandiff.excel.stax.readers.BufferingReader.hasNext(BufferingReader.java:87)
		... 18 more
	Suppressed: xyz.hotchpotch.hogandiff.excel.ExcelHandlingException: Excelファイルのコピーに失敗しました：▲▲▲■■■.xlsm -> ●●●【A】■■■.xlsm
		at xyz.hotchpotch.hogandiff.excel.poi.usermodel.BookPainterWithPoiUserApi.paintAndSave(BookPainterWithPoiUserApi.java:167)
		at xyz.hotchpotch.hogandiff.excel.common.CombinedBookPainter.paintAndSave(CombinedBookPainter.java:107)
		... 11 more
	Caused by: java.nio.file.FileAlreadyExistsException: ●●●【A】■■■.xlsm
		at java.base/sun.nio.fs.WindowsFileCopy.copy(Unknown Source)
		at java.base/sun.nio.fs.WindowsFileSystemProvider.copy(Unknown Source)
		at java.base/java.nio.file.Files.copy(Unknown Source)
		at xyz.hotchpotch.hogandiff.excel.poi.usermodel.BookPainterWithPoiUserApi.paintAndSave(BookPainterWithPoiUserApi.java:157)
		... 12 more

```

セルコメント加工処理において、
StAXがXML空要素の終了タグ省略を許容していないために
元データに含まれる <br> タグの処理に失敗しているように見受けられる。

**Comment by nmby** [comment]
メモ：
シンプルな .xlsx ファイルで確認する限りでは、\xl\drawings\vmlDrawing?.vml エントリに <br> タグが入り込む余地はないように感じる。
VMLとは：http://www.doraneko.org/misc/vml/19980513/Overview.html

ファイルパース時の文字コードが関係？：https://oshiete.goo.ne.jp/qa/3173427.html
現在はUTF-8としてパースしている。：https://github.com/nmby/hogandiff3/blob/4ba589ed953634be75447406cf9c2b6d5325bae9/xyz.hotchpotch.hogandiff/src/main/java/xyz/hotchpotch/hogandiff/excel/stax/XSSFBookPainterWithStax.java#L596

バグの再現が困難であるため、当該 Exception がスローされた際は対象 vml ファイルの処理を諦め後続処理を続ける方向で検討する。
